# This file store and manage social-media posts generated by the chatbot

from typing import List , Optional , Dict , Any
from uuid import UUID
from datetime import datetime

from sqlalchemy import select , update
from app.config import get_db_session
from app.db.postgres.models import Chat, Message , Post

# ----------------------------------------- Conversation State Management -----------------------------------------------
CONVERSTION_STATES = {
    "IDLE": "Waiting for user input",
    "MODE_SELECTION": "Choosing advertisment or general",
    "COLLECTING_PRODUCT_INFO": "Getting product details",
    "GENERATING_IMAGE": "AI generating image",
    "GENERATING_CAPTION": "AI generating caption",
    "PREVIEW": "Showing preview before publish",
    "PUBLISHING": "Publishing to social media",
    "COMPLETED": "Task completed"

}

# ------------------------- Getting chat context -----------------------------------------------
def get_chat_context(chat_id: UUID , user_id: int) -> Optional[Dict[str,Any]]:
    with get_db_session() as session:
        chat_stmt = select(Chat).where(Chat.id == chat_id, Chat.user_id == user_id)

        if not chat:
            return None

        msg_stmt = (select(Message).where(Message.chat_id == chat_id).order_by(Message.created_at.desc())
        .limit(10))
        messages = session.execute(msg_stmt).scalars().all()

        # Get associated post if any
        post_stmt = select(Post).where(Post.chat_id == chat_id).order_by(Post.created_at.dec().limit(1))
        post = session.execute(post_stmt).scalars().first()

        return {
            "chat_id": str(chat.id),
            "user_id": chat.user_id,
            "title": chat.title,
            "state": "IDLE",  # You can add a 'state' column to Chat model
            "messages": [
                {
                    "role": "user" if m.author_firebase_uid else "assistant",
                    "content": m.input.get("text", "") if m.input else "",
                    "created_at": m.created_at
                }
                for m in reversed(list(messages))
            ],
            "current_post": {
                "id": str(post.id),
                "mode": post.mode,
                "status": post.status,
                "description": post.description,
                "image_url": post.image_url,
                "caption": post.caption,
            } if post else None
        }


#  ---------------------------------------------- Updating Chat State ---------------------------------------------
def update_chat_state(chat_id: UUID, state: str, context_data: Optional[Dict] = None) -> bool;
    with get_db_session()as session:
        update_stmt = (
            update(Chat)
            .where(Chat.id == chat_id)
            .values(updated_at=datetime.now())
        )
        session.execute(update_stmt)
        session.flush()
        return True

#  ---------------------------------------------- Getting Conversation History ---------------------------------------------
def get_conversation_history(chat_id: UUID , limit: int = 10) -> List[Dict]:
    with get_db_session() as session:
        stmt = (
            select(Message)
            .where(Message.chat_id == chat_id)
            .order_by(Message.cretaed_at.asc())
            .limit(limit)
        )
        messages= session.execute(stmt).scalars().all()

